version: '3.7'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - 8000:8000
    expose:
      - 8000
